# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Daniil Tiganov
description:
repository: https://github.com/tiganov/tiganov.github.io
baseurl: /tiganov.github.io  # the subpath of your site, e.g. /blog
url: https://tiganov.ca  # the base hostname & protocol for your site
name: Daniil Tiganov

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: standard  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Daniil Tiganov
email: tiganov@ualberta.ca

navigation:
  - text: About me
    url: /
  - text: Projects
    url: /projects
  - text: CV
    url: /cv.pdf

about_description: "Computing Science undergraduate student at the University of Alberta.
Working at the Maple lab under Dr. Karim Ali during the summer/fall of 2019."

about_me: "I was born in Chisinau, Moldova, and my family immigrated to Canada in 2004. I grew up in small farming town in North-Eastern Saskatchewan. During my childhood, I spent just as much time behind a computer as I did working with my hands; whether it was working on cars with my dad, landscaping, or working on construction projects. I graduated high school in 2016, and moved to Edmonton to study at the University of Alberta."

research_area: "I am interested in program analysis tools that can be deployed and used by developers in the industry. I put high priority in making software usable and maintainable. Unlike many current program analysis tools and frameworks, I want my work to be well documented and easy to integrate into developers workflows and development processes."

projects:
  - name: SWAN - A program analysis framework for Swift
    description: SWAN is the first open source static program analysis framework for Swift meant to enable analysis such as CHA, call graphs, pointer analysis,taint analysis, etc. The translator is written in C++, hooks into the Swift compiler, translates the raw SIL to WALA CAst, and passes the translated IR up to the analysisengine built on top of WALA and written in Java. Currently, I am the main contributor to SWAN.
    link: https://github.com/themaplelab/swan
    image: images/swan.png

  - name: Swasar - Swift implementation for Phasar
    description: This project is an attempt at implementing taint analysis on pure Swift applications using the LLVM static program analysis framework, Phasar. LLVM IR generated from the Swift compiler is fed to a modified Phasar analysis to find the presence of taints in the Swift source code. The taint analysis was successful, but using an LLVM analysis framework is not ideal for analyzing Swift applications.
    link: https://github.com/tiganov/swasar
    image: images/phasar.png

  - name: QuickTopo
    description: I currently lead a team of 3 other developers under the name Prairium. We are working on developing an independent commercial solution, QuickTopo, to address a bottleneck in the topological surveying process, especially in the area of agriculture. I have developed and used a prototype for this software when I was working as a surveyor for Greentree Engineering. We hope any surveyor needing to do a significant topological survey can utilize our tool to save time and money.
    image: images/prairium.png

  - name: CloudCity - A city building game written for HackEd 2019
    description: My team and I developed a simple city building game about population management using openFrameworks.
    image: images/cloudcity.png
    link: https://github.com/nickdchee/CityBuilderRTS

  - name: CAT - Cluedo Assistant Tool
    description: I made a simple desktop application using WPF to assist in keeping track of moves and cards in the game of Cluedo.
    image: images/cat.png
    link: https://github.com/tiganov/CAT

  - name: DoctorPlzSaveMe - a medical app developed for CMPUT 301 (Intro to Software Engineering)
    description: I took on the role of project lead and backend developer for this course project. We developed an app that allows users to track/record their medical issues and receive feedback from a care provider.
    image: images/doctorplzsaveme.png
    link: https://github.com/CMPUT301F18T21/DoctorPlzSaveMe

  - name: Starcraft 2 bot - a bot developed for CMPUT 350 (Advanced Game Programming)
    description: I helped develop a bot based on CommandCenter, and pitted it against other teams’ bots. I worked on siege tank and resource gathering AI.
    link: https://github.com/tiganov/PatientBot
    image: images/sc2.png

  - name: Black Hole Visualizer
    description: I attempted to visualize a spinning black hole using openFrameworks for an ASTRO creative assignment. It was difficult to do, but the result is good enough to roughly represent how particles are affected by a black hole. This work was later presented at a teaching conference by one of the course coordinators.
    link: https://github.com/tiganov/BHSim
    image: images/bhsim.png

  - name: Laser Tag Pistol
    description: I 3D-printed, built, and programmed a custom laser tag pistol. It uses a Teensy for a micro-controller, produces various sounds, has LED animations, and can receive/send unique IR signals (to be able to differentiate between teams, for instance).
    link_video: https://www.youtube.com/watch?v=VDHNdLiEAhM&feature=youtu.be
    image: images/laser.JPG

  - name: Automatic deadbolt unlocker
    description: I 3D printed, built, and programmed a remote-based automatic deadbolt opener for my dorm.
    link_video: https://www.youtube.com/watch?v=exouNxdYlAY&feature=youtu.be
    image: images/dorm.jpeg

  - name: Control panel for flight sims
    description: I started making a control panel for Elite Dangerous (space flight sim game), but never finished it. WIP, mostly abandoned.
    image: images/controlpanel.png

interests:
  - Programming languages
  - Static program analysis
  - Computer architecture
  - Software architecture and design patterns
  - Creative programming (openFrameworks)
  - GIS software solutions
  - Land Surveying
  - Industrial Automation
  - Electronics (tinkering)
  - CAD software

skills:
  - C++, Java, C, JavaScript, Python, MIPS Assembly, C#
  - WALA (static analysis framework for Java, Python, Javascript)
  - Static program analysis (IFDS, call graphs, CFG, pointer analysis, taint analysis, constant propagation, field-based and field-(in)sensitive analysis)
  - Experience with Swift compiler frontend
  - openFrameworks (C++ creative coding framework used for many of my projects)
  - WPF (for Cluedo Assistant Tool) and JavaFX
  - Android Studio (for CMPUT 301 project)
  - Microcontroller programming (Arduino, Teensy)
  - Land Surveying (Trimble TSC3, SurveyPro)
  - SolidWorks

academic_achievements_university:
  - Deans Honour Roll for Fa17/Wi18
  - Deans Honour Roll for Fa18/Wi19
  - Current GPA ~3.6

academic_achievements_high_school:
  - Fast tracked high school education by one year
  - Certificate of Academic Excellence for Physics 30 and Law 30
  - Cornerstone Credit Union Scholarship for Fifth Highest Academic Standing
  - Harley & Hazel Ransom Memorial Scholarship for Post-Secondary Studies in Engineering

work_experience:
- title: Research Assistant (Current)
  loc: University of Alberta
  when: May 2019 - Aug 2019
  desc: Working on SWAN, a static analysis framework for Swift applications. 
- title: General Labourer/Surveyor
  loc: Greentree Engineering - Tisdale, Saskatchewan
  when: May 2018 - Aug 2018
  desc: Personal property maintenance, laser scanning, surveying, automating surveying tools, staking roads, concrete foundations, and excavation.
- title: General Labourer
  loc: Greentree Engineering - Tisdale, Saskatchewan
  when: Jun 2017 - Aug 2017
  desc: Maintained 7 properties. Renovated house - demolition, drywall, plumbing, electrical, windows installation, wall framing. Misc. jobs - mechanical upkeep, hauling trailers, shed assembly, etc.
- title: Student Position
  loc: Beeland Co-op Home Center - Tisdale, Saskatchewan
  when: Jul 2015 - Jun 2016
  desc: Provided support to customers regarding paint, plumbing, electrical, vanities, electric mowers, yard tractors, and tools. Assembled yard tractors, trailers, and air compressors.

social:
  - service: github
    username: tiganov
    link: https://github.com/tiganov
  - service: linkedin
    username: daniil-tiganov
    link: https://www.linkedin.com/in/daniil-tiganov/

# Plugins
gems:
  - jekyll-seo-tag
